#!/bin/bash

helpcmd="-help"
setcmd="-set"
activecmd="-active"
PATH_NAME=$(pwd)
DATE=$(date +%Y%m%d)
PASSWORD="1234"
if [ $1 == $helpcmd ]
then
	cat ybm_helper_ui
elif [ $1 == $setcmd ]
then
       echo "order check : make back up folder"
       $(mkdir backup)
       echo "mkdir backup"
       $(chmod 755 backup)
       echo "chmod 755 for backup folder"
       echo "finished your order"
       echo "back up folder is $PATH_NAME / backup"
elif [ $1 == $activecmd ]
then
	sh backup_order.sh
else
       echo "please check your order for use this command (-help)"
fi
